---
title: "Prediction"
output: html_document
---

```{r}
library(tidyverse)
library(readr)


library(mgcv)     
library(rsample)  
library(yardstick)
library(broom)    
library(gratia)   

library(patchwork)
```

```{r}
train <- read_csv("data-train.csv")

train <- train %>%
  mutate(
    mu = R_moment_1,
    sigma = sqrt(R_moment_2 - R_moment_1^2),
    skew = (R_moment_3 - 3*R_moment_2*R_moment_1 + 2*R_moment_1^3) / sigma^3,
    kurt = (R_moment_4 - 4*R_moment_3*R_moment_1 + 6*R_moment_2*R_moment_1^2 - 3*R_moment_1^4) / sigma^4
  )
```

## EDA

```{r}
pairs(~ Re + Fr + St + mu + sigma + skew + kurt, data=train)
```






# GAM

```{r}
# shared formula template (log-inputs for smoother shapes)
f_base <- as.formula(
  y ~ s(logRe, k=10) + s(logFr, k=10) + s(logSt, k=10) +
      ti(logRe, logFr, k=c(6,6)) + ti(logRe, logSt, k=c(6,6)) + ti(logFr, logSt, k=c(6,6))
)

set.seed(42)
folds <- vfold_cv(train, v = 10, strata = NULL)

fit_gam_cv <- function(df, response, f_template=f_base) {
  # build formula with the chosen response
  f <- update(f_template, paste(response, "~ ."))
  # CV loop
  metrics <- map_df(folds$splits, function(s) {
    tr <- analysis(s); te <- assessment(s)
    m  <- gam(f, data=tr, method="REML", select=TRUE)  # select=TRUE does smoother shrinkage
    preds <- predict(m, newdata=te)
    tibble(
      rmse = rmse_vec(truth = te[[response]], estimate = preds),
      mae  = mae_vec( truth = te[[response]], estimate = preds),
      rsq  = rsq_vec( truth = te[[response]], estimate = preds)
    )
  })
  summarised <- summarise_all(metrics, mean)
  list(cv = summarised)
}

cv_mu    <- fit_gam_cv(train, "mu")
cv_sigma <- fit_gam_cv(train, "sigma")
cv_skew  <- fit_gam_cv(train, "skew")
cv_kurt  <- fit_gam_cv(train, "kurt")

bind_rows(
  mutate(cv_mu$cv,    target="mu"),
  mutate(cv_sigma$cv, target="sigma"),
  mutate(cv_skew$cv,  target="skew"),
  mutate(cv_kurt$cv,  target="kurt")
) %>% arrange(target)

```

